export const SYSTEM_EVENT_TYPES = {
  LEAD_CREATED: "LEAD_CREATED",
  ONBOARDING_SENT: "ONBOARDING_SENT",
  ONBOARDING_COMPLETED: "ONBOARDING_COMPLETED",
  CLIENT_CREATED: "CLIENT_CREATED",
  GA4_CONNECTED: "GA4_CONNECTED",
  GBP_CONNECTED: "GBP_CONNECTED",
  GSC_CONNECTED: "GSC_CONNECTED",
  RANK_UPDATED: "RANK_UPDATED",
  METRICS_SYNCED: "METRICS_SYNCED",
  REPORT_GENERATED: "REPORT_GENERATED",
  PORTAL_LOGIN: "PORTAL_LOGIN",
} as const;

export type SystemEventType =
  (typeof SYSTEM_EVENT_TYPES)[keyof typeof SYSTEM_EVENT_TYPES];
