import type { Task } from "@prisma/client";
import { Badge } from "@/components/ui/badge";

interface LeadTasksListProps {
  tasks: Task[];
}

export function LeadTasksList({ tasks }: LeadTasksListProps) {
  if (tasks.length === 0) {
    return <p className="text-sm text-muted">No tasks yet.</p>;
  }

  return (
    <ul className="divide-y divide-border rounded-lg border border-border">
      {tasks.map((task) => (
        <li key={task.id} className="flex items-center justify-between gap-3 px-4 py-3">
          <div className="min-w-0">
            <p className="text-sm text-foreground truncate">{task.title}</p>
            {task.autoGenerated && (
              <p className="text-xs text-muted">Auto-generated on lead creation</p>
            )}
          </div>
          <Badge variant={task.status === "DONE" ? "success" : "muted"}>
            {task.status}
          </Badge>
        </li>
      ))}
    </ul>
  );
}
