import type {
  AccessSystemType,
  OnboardingRule,
  OnboardingStage,
  OnboardingTemplate,
  Prisma,
} from "@prisma/client";
import { randomBytes } from "crypto";
import { prisma } from "@/lib/prisma";
import { LAUNCH_SOP_ITEMS } from "@/lib/blueprint/launch-sops";
import { PRICING_PACKAGES } from "@/lib/blueprint/pricing-packages";
import { hydrateClientFromOnboardingAnswers } from "./hydrate-from-answers";
import { evaluateCondition } from "./rules";
import { emitSystemEvent } from "@/lib/events/emit";
import { SYSTEM_EVENT_TYPES } from "@/lib/events/types";
import { encrypt, isEncryptionConfigured } from "@/lib/crypto/encryption";
import {
  CORE_ACCESS_REQUESTS,
  clientStatusFromPackages,
  markStageComplete,
  nextStage,
  packagesToInterestedIn,
  parseCompletedStages,
  type AccessHandoffItem,
} from "./stages";

type Answers = Record<string, unknown>;

const GA_SETUP_STEPS = [
  { label: "Create or confirm Google Analytics account", systemType: null },
  { label: "Create GA4 property for client domain", systemType: "GA4" as AccessSystemType },
  { label: "Install GA4 tag on website", systemType: null },
  { label: "Verify realtime data in GA4", systemType: "GA4" as AccessSystemType },
  { label: "Connect GA4 (OAuth or Property ID)", systemType: "GA4" as AccessSystemType },
  { label: "Add agency email as GA4 viewer", systemType: "GA4" as AccessSystemType },
  { label: "Verify domain in Google Search Console", systemType: "SEARCH_CONSOLE" as AccessSystemType },
  { label: "Connect Google Search Console", systemType: "SEARCH_CONSOLE" as AccessSystemType },
  { label: "Submit sitemap in GSC", systemType: "SEARCH_CONSOLE" as AccessSystemType },
  { label: "Confirm tracked keywords from onboarding", systemType: null },
];

async function seedLaunchSopItems(clientId: string) {
  const labels = LAUNCH_SOP_ITEMS.map((item) => item.label);
  const existing = await prisma.launchChecklistItem.count({
    where: { clientId, label: { in: labels } },
  });
  if (existing > 0) return;

  await prisma.launchChecklistItem.createMany({
    data: LAUNCH_SOP_ITEMS.map((item) => ({
      clientId,
      label: item.label,
      order: item.order,
    })),
  });
}

export async function ensureClientFromLead(leadId: string) {
  const lead = await prisma.lead.findUnique({
    where: { id: leadId },
    include: { client: true },
  });
  if (!lead) throw new Error("Lead not found");
  if (lead.client) return lead.client;

  return prisma.client.create({
    data: {
      leadId: lead.id,
      legalBusinessName: lead.businessName,
      billingName: lead.contactName,
      billingEmail: lead.email,
      primaryContactName: lead.contactName,
      primaryContactPhone: lead.phone,
      status: "ONBOARDING",
      brandProfile: {
        create: {
          phonePrimary: lead.phone,
          industry: lead.industry,
          serviceAreas: lead.serviceArea ? [lead.serviceArea] : [],
          existingSiteUrl: lead.website,
          budgetRange: lead.budgetRange,
          domain: lead.website?.replace(/^https?:\/\//, "").split("/")[0],
          gbpCategoriesSecondary: [],
          exampleSites: [],
        },
      },
    },
  });
}

async function ensureAccessItem(
  clientId: string,
  systemType: AccessSystemType,
  label: string
) {
  const existing = await prisma.accessChecklistItem.findFirst({
    where: { clientId, systemType, label },
  });
  if (existing) {
    if (existing.status === "NOT_REQUESTED") {
      await prisma.accessChecklistItem.update({
        where: { id: existing.id },
        data: { status: "REQUESTED", requestedAt: new Date() },
      });
    }
    return existing;
  }
  return prisma.accessChecklistItem.create({
    data: {
      clientId,
      systemType,
      label,
      status: "REQUESTED",
      requestedAt: new Date(),
    },
  });
}

export async function seedCoreAccessRequests(clientId: string) {
  for (const item of CORE_ACCESS_REQUESTS) {
    await ensureAccessItem(clientId, item.systemType, item.label);
  }
}

async function applyRule(
  rule: OnboardingRule,
  clientId: string,
  leadId: string,
  answers: Answers
) {
  const config = rule.outputConfig as Record<string, unknown>;

  switch (rule.outputType) {
    case "TASK": {
      const title = String(config.title ?? "Follow up");
      const existing = await prisma.task.findFirst({
        where: { clientId, title, source: "onboarding" },
      });
      if (existing) break;
      await prisma.task.create({
        data: {
          clientId,
          leadId,
          title,
          description: config.description ? String(config.description) : null,
          autoGenerated: true,
          source: "onboarding",
        },
      });
      break;
    }

    case "ACCESS_CHECKLIST":
      await ensureAccessItem(
        clientId,
        (config.systemType as AccessSystemType) ?? "OTHER",
        String(config.label ?? "Access item")
      );
      break;

    case "LAUNCH_CHECKLIST": {
      const label = String(config.label ?? "Launch item");
      const existing = await prisma.launchChecklistItem.findFirst({
        where: { clientId, label },
      });
      if (!existing) {
        await prisma.launchChecklistItem.create({
          data: {
            clientId,
            label,
            order: Number(config.order ?? 0),
          },
        });
      }
      break;
    }

    case "BRAND_PROFILE_FIELD": {
      const field = String(config.field ?? "");
      const value = answers[String(config.answerKey ?? field)];
      if (field && value != null) {
        await prisma.brandProfile.update({
          where: { clientId },
          data: { [field]: value } as Prisma.BrandProfileUpdateInput,
        });
      }
      break;
    }

    case "INTEGRATION_CHECKLIST":
      for (const [index, step] of GA_SETUP_STEPS.entries()) {
        if (step.systemType) {
          await ensureAccessItem(clientId, step.systemType, step.label);
        } else {
          const existing = await prisma.launchChecklistItem.findFirst({
            where: { clientId, label: step.label },
          });
          if (!existing) {
            await prisma.launchChecklistItem.create({
              data: {
                clientId,
                label: step.label,
                order: index,
              },
            });
          }
        }
      }
      break;

    case "PROPOSAL_LINE": {
      const pricingId = config.pricingMatrixItemId
        ? String(config.pricingMatrixItemId)
        : null;
      const item = pricingId
        ? await prisma.pricingMatrixItem.findUnique({ where: { id: pricingId } })
        : null;

      let proposal = await prisma.proposal.findFirst({
        where: { clientId, status: "DRAFT" },
      });

      if (!proposal) {
        proposal = await prisma.proposal.create({
          data: { clientId, status: "DRAFT" },
        });
      }

      const unitPrice = item?.basePrice ?? 0;
      const qty = Number(config.quantity ?? 1);
      await prisma.proposalLineItem.create({
        data: {
          proposalId: proposal.id,
          description: item?.name ?? String(config.description ?? "Service"),
          quantity: qty,
          unitPrice,
          total: Number(unitPrice) * qty,
        },
      });
      break;
    }

    case "INVOICE_DRAFT": {
      const pricingId = config.pricingMatrixItemId
        ? String(config.pricingMatrixItemId)
        : null;
      const item = pricingId
        ? await prisma.pricingMatrixItem.findUnique({ where: { id: pricingId } })
        : null;

      const unitPrice = Number(config.unitPrice ?? item?.basePrice ?? 0);
      const qty = Number(config.quantity ?? 1);
      const total = unitPrice * qty;
      const invoiceType =
        (config.invoiceType as "DEPOSIT" | "MILESTONE" | "FINAL" | "RETAINER" | "ONE_OFF") ??
        "DEPOSIT";

      let invoice = await prisma.invoice.findFirst({
        where: { clientId, status: "DRAFT", type: invoiceType },
      });

      if (!invoice) {
        invoice = await prisma.invoice.create({
          data: {
            clientId,
            type: invoiceType,
            status: "DRAFT",
            totalAmount: total,
            currency: String(config.currency ?? "CAD"),
          },
        });
      } else {
        await prisma.invoice.update({
          where: { id: invoice.id },
          data: { totalAmount: Number(invoice.totalAmount) + total },
        });
      }

      await prisma.invoiceLineItem.create({
        data: {
          invoiceId: invoice.id,
          description: item?.name ?? String(config.description ?? "Onboarding service"),
          quantity: qty,
          unitPrice,
          total,
        },
      });
      break;
    }

    default:
      break;
  }
}

async function applyRulesForAnswers(
  template: OnboardingTemplate & { rules: OnboardingRule[] },
  clientId: string,
  leadId: string,
  answers: Answers
) {
  for (const rule of template.rules) {
    if (evaluateCondition(rule.condition, answers)) {
      await applyRule(rule, clientId, leadId, answers);
    }
  }
}

function mergeResponses(
  existing: unknown,
  next: Answers
): Answers {
  const base =
    existing && typeof existing === "object" && !Array.isArray(existing)
      ? { ...(existing as Answers) }
      : {};
  return { ...base, ...next };
}

export async function completeProfileStage(input: {
  sessionId: string;
  leadId: string;
  template: OnboardingTemplate & { rules: OnboardingRule[] };
  responses: Answers;
}) {
  const client = await ensureClientFromLead(input.leadId);
  await seedLaunchSopItems(client.id);
  await hydrateClientFromOnboardingAnswers(client.id, input.responses);
  await seedCoreAccessRequests(client.id);

  const session = await prisma.onboardingSession.findUniqueOrThrow({
    where: { id: input.sessionId },
  });
  const completed = markStageComplete(
    parseCompletedStages(session.completedStages),
    "PROFILE"
  );
  const merged = mergeResponses(session.responses, input.responses);

  await prisma.onboardingSession.update({
    where: { id: input.sessionId },
    data: {
      clientId: client.id,
      responses: merged as Prisma.InputJsonValue,
      status: "IN_PROGRESS",
      currentStage: "PACKAGES",
      completedStages: completed as Prisma.InputJsonValue,
    },
  });

  await prisma.lead.update({
    where: { id: input.leadId },
    data: { status: "QUESTIONNAIRE_COMPLETED" },
  });

  return { client, nextStage: "PACKAGES" as OnboardingStage };
}

export async function completePackagesStage(input: {
  sessionId: string;
  clientId: string;
  packageIds: string[];
  template: OnboardingTemplate & { rules: OnboardingRule[] };
  leadId: string;
}) {
  const pkgs = input.packageIds
    .map((id) => PRICING_PACKAGES.find((p) => p.id === id))
    .filter((p): p is (typeof PRICING_PACKAGES)[number] => Boolean(p));

  if (!pkgs.length) throw new Error("No valid packages selected");

  const scopeParts = pkgs.map((p) => `${p.name}: ${p.scopeIncluded}`);
  const monthlyTotal = pkgs
    .filter((p) => p.unit === "monthly")
    .reduce(
      (sum, p) => sum + p.lineItems.reduce((s, li) => s + li.unitPrice, 0),
      0
    );

  const session = await prisma.onboardingSession.findUniqueOrThrow({
    where: { id: input.sessionId },
  });

  // Replace any prior draft proposal from this session
  if (session.proposalId) {
    const oldId = session.proposalId;
    await prisma.onboardingSession.update({
      where: { id: input.sessionId },
      data: { proposalId: null },
    });
    await prisma.proposalLineItem.deleteMany({
      where: { proposalId: oldId },
    });
    await prisma.proposal.delete({ where: { id: oldId } }).catch(() => {});
  }

  const signToken = randomBytes(32).toString("hex");
  const proposal = await prisma.proposal.create({
    data: {
      clientId: input.clientId,
      status: "SENT",
      scopeIncluded: scopeParts.join("\n\n"),
      signToken,
      signTokenExpiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      retainerTerms:
        monthlyTotal > 0
          ? ({
              monthlyFee: monthlyTotal,
              cadence: "monthly",
              noticePeriodDays: 30,
              autoRenew: true,
            } as Prisma.InputJsonValue)
          : undefined,
      lineItems: {
        create: pkgs.flatMap((pkg) =>
          pkg.lineItems.map((item) => ({
            description: `${pkg.name} — ${item.description}`,
            quantity: 1,
            unitPrice: item.unitPrice,
            total: item.unitPrice,
          }))
        ),
      },
    },
  });

  const interestedIn = packagesToInterestedIn(input.packageIds);
  const merged = mergeResponses(session.responses, {
    selectedPackages: input.packageIds,
    interestedIn,
  });

  await applyRulesForAnswers(
    input.template,
    input.clientId,
    input.leadId,
    merged
  );

  const completed = markStageComplete(
    parseCompletedStages(session.completedStages),
    "PACKAGES"
  );

  await prisma.onboardingSession.update({
    where: { id: input.sessionId },
    data: {
      proposalId: proposal.id,
      selectedPackages: input.packageIds as Prisma.InputJsonValue,
      responses: merged as Prisma.InputJsonValue,
      currentStage: "AGREEMENT",
      completedStages: completed as Prisma.InputJsonValue,
      status: "IN_PROGRESS",
    },
  });

  return { proposal, nextStage: "AGREEMENT" as OnboardingStage };
}

export async function completeAgreementStage(input: {
  sessionId: string;
  proposalId: string;
  signatureDataUrl: string;
  signedIp?: string;
}) {
  const proposal = await prisma.proposal.findUnique({
    where: { id: input.proposalId },
  });
  if (!proposal) throw new Error("Proposal not found");

  await prisma.proposal.update({
    where: { id: input.proposalId },
    data: {
      status: "SIGNED",
      signatureDataUrl: input.signatureDataUrl,
      signedAt: new Date(),
      signedIp: input.signedIp ?? null,
      signToken: null,
      signTokenExpiresAt: null,
    },
  });

  const session = await prisma.onboardingSession.findUniqueOrThrow({
    where: { id: input.sessionId },
  });
  const completed = markStageComplete(
    parseCompletedStages(session.completedStages),
    "AGREEMENT"
  );

  if (session.leadId) {
    await prisma.lead.update({
      where: { id: session.leadId },
      data: { status: "WON" },
    });
  }

  await prisma.onboardingSession.update({
    where: { id: input.sessionId },
    data: {
      currentStage: "ACCESS",
      completedStages: completed as Prisma.InputJsonValue,
      status: "IN_PROGRESS",
    },
  });

  await emitSystemEvent({
    type: "CLIENT_CREATED",
    clientId: proposal.clientId,
    payload: { action: "proposal_signed_onboarding", proposalId: proposal.id },
  });

  return { nextStage: "ACCESS" as OnboardingStage };
}

export async function completeAccessStage(input: {
  sessionId: string;
  clientId: string;
  leadId: string;
  items: AccessHandoffItem[];
  packageIds: string[];
}) {
  for (const item of input.items) {
    const accessItem = await prisma.accessChecklistItem.findFirst({
      where: { id: item.accessItemId, clientId: input.clientId },
    });
    if (!accessItem) continue;

    if (item.mode === "na") {
      await prisma.accessChecklistItem.update({
        where: { id: accessItem.id },
        data: {
          status: "RECEIVED",
          receivedAt: new Date(),
          notes: "Client marked not applicable",
        },
      });
      continue;
    }

    if (item.mode === "invite") {
      await prisma.accessChecklistItem.update({
        where: { id: accessItem.id },
        data: {
          status: "RECEIVED",
          receivedAt: new Date(),
          notes: `Invite shared: ${(item.inviteNotes ?? "").trim()}`,
        },
      });
      continue;
    }

    // credentials
    if (!isEncryptionConfigured()) {
      throw new Error(
        "ENCRYPTION_KEY is not configured. Share access via invite instead, or ask the agency to set ENCRYPTION_KEY."
      );
    }

    const entry = await prisma.credentialVaultEntry.create({
      data: {
        clientId: input.clientId,
        label: accessItem.label,
        url: item.url?.trim() || null,
        usernameEnc: item.username?.trim()
          ? encrypt(item.username.trim())
          : null,
        passwordEnc: item.password?.trim()
          ? encrypt(item.password.trim())
          : null,
        notesEnc: item.notes?.trim() ? encrypt(item.notes.trim()) : null,
      },
    });

    await prisma.vaultAccessLog.create({
      data: { entryId: entry.id, action: "CREATE" },
    });

    await prisma.accessChecklistItem.update({
      where: { id: accessItem.id },
      data: {
        status: "RECEIVED",
        receivedAt: new Date(),
        notes: "Credentials stored in encrypted vault",
      },
    });
  }

  const status = clientStatusFromPackages(input.packageIds);
  await prisma.client.update({
    where: { id: input.clientId },
    data: { status },
  });

  const session = await prisma.onboardingSession.findUniqueOrThrow({
    where: { id: input.sessionId },
  });
  const completed = markStageComplete(
    parseCompletedStages(session.completedStages),
    "ACCESS"
  );
  completed.push("COMPLETED");

  await prisma.onboardingSession.update({
    where: { id: input.sessionId },
    data: {
      status: "COMPLETED",
      currentStage: "COMPLETED",
      completedStages: completed as Prisma.InputJsonValue,
      completedAt: new Date(),
    },
  });

  await emitSystemEvent({
    type: SYSTEM_EVENT_TYPES.ONBOARDING_COMPLETED,
    clientId: input.clientId,
    leadId: input.leadId,
    payload: { sessionId: input.sessionId, clientStatus: status },
  });

  return { nextStage: "COMPLETED" as const, clientStatus: status };
}

/** Legacy single-shot submit — runs full pipeline for backwards compatibility. */
export async function processOnboardingSubmission(input: {
  sessionId: string;
  token: string;
  responses: Answers;
  template: OnboardingTemplate & { rules: OnboardingRule[] };
  leadId: string;
}) {
  await completeProfileStage({
    sessionId: input.sessionId,
    leadId: input.leadId,
    template: input.template,
    responses: input.responses,
  });

  // Legacy path: mark completed without packages/agreement/access
  await prisma.onboardingSession.update({
    where: { id: input.sessionId },
    data: {
      status: "COMPLETED",
      currentStage: "COMPLETED",
      completedAt: new Date(),
      completedStages: [
        "PROFILE",
        "COMPLETED",
      ] as Prisma.InputJsonValue,
    },
  });

  const client = await prisma.client.findFirstOrThrow({
    where: { leadId: input.leadId },
  });

  await applyRulesForAnswers(
    input.template,
    client.id,
    input.leadId,
    input.responses
  );

  await emitSystemEvent({
    type: SYSTEM_EVENT_TYPES.ONBOARDING_COMPLETED,
    clientId: client.id,
    leadId: input.leadId,
    payload: { sessionId: input.sessionId, legacy: true },
  });

  return client;
}

export { nextStage };
