import type {
  AccessSystemType,
  OnboardingRule,
  OnboardingTemplate,
  Prisma,
} from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { evaluateCondition } from "./rules";
import { emitSystemEvent } from "@/lib/events/emit";
import { SYSTEM_EVENT_TYPES } from "@/lib/events/types";

type Answers = Record<string, unknown>;

const GA_SETUP_STEPS = [
  { label: "Create or confirm Google Analytics account", systemType: null },
  { label: "Create GA4 property for client domain", systemType: "GA4" as AccessSystemType },
  { label: "Install GA4 tag on website", systemType: null },
  { label: "Verify realtime data in GA4", systemType: "GA4" as AccessSystemType },
  { label: "Connect GA4 (OAuth or Property ID)", systemType: "GA4" as AccessSystemType },
  { label: "Add agency email as GA4 viewer", systemType: "GA4" as AccessSystemType },
  { label: "Verify domain in Google Search Console", systemType: "SEARCH_CONSOLE" as AccessSystemType },
  { label: "Connect Google Search Console", systemType: "SEARCH_CONSOLE" as AccessSystemType },
  { label: "Submit sitemap in GSC", systemType: "SEARCH_CONSOLE" as AccessSystemType },
  { label: "Confirm tracked keywords from onboarding", systemType: null },
];

async function ensureClientFromLead(leadId: string) {
  const lead = await prisma.lead.findUnique({
    where: { id: leadId },
    include: { client: true },
  });
  if (!lead) throw new Error("Lead not found");
  if (lead.client) return lead.client;

  return prisma.client.create({
    data: {
      leadId: lead.id,
      legalBusinessName: lead.businessName,
      billingName: lead.contactName,
      billingEmail: lead.email,
      status: "ONBOARDING",
      brandProfile: {
        create: {
          phonePrimary: lead.phone,
          industry: lead.industry,
          serviceAreas: lead.serviceArea ? [lead.serviceArea] : [],
          existingSiteUrl: lead.website,
          budgetRange: lead.budgetRange,
          domain: lead.website?.replace(/^https?:\/\//, "").split("/")[0],
          gbpCategoriesSecondary: [],
          exampleSites: [],
        },
      },
    },
  });
}

async function applyRule(
  rule: OnboardingRule,
  clientId: string,
  leadId: string,
  answers: Answers
) {
  const config = rule.outputConfig as Record<string, unknown>;

  switch (rule.outputType) {
    case "TASK":
      await prisma.task.create({
        data: {
          clientId,
          leadId,
          title: String(config.title ?? "Follow up"),
          description: config.description ? String(config.description) : null,
          autoGenerated: true,
          source: "onboarding",
        },
      });
      break;

    case "ACCESS_CHECKLIST":
      await prisma.accessChecklistItem.create({
        data: {
          clientId,
          systemType: (config.systemType as AccessSystemType) ?? "OTHER",
          label: String(config.label ?? "Access item"),
          status: "REQUESTED",
          requestedAt: new Date(),
        },
      });
      break;

    case "LAUNCH_CHECKLIST":
      await prisma.launchChecklistItem.create({
        data: {
          clientId,
          label: String(config.label ?? "Launch item"),
          order: Number(config.order ?? 0),
        },
      });
      break;

    case "BRAND_PROFILE_FIELD": {
      const field = String(config.field ?? "");
      const value = answers[String(config.answerKey ?? field)];
      if (field && value != null) {
        await prisma.brandProfile.update({
          where: { clientId },
          data: { [field]: value } as Prisma.BrandProfileUpdateInput,
        });
      }
      break;
    }

    case "INTEGRATION_CHECKLIST":
      for (const [index, step] of GA_SETUP_STEPS.entries()) {
        if (step.systemType) {
          await prisma.accessChecklistItem.create({
            data: {
              clientId,
              systemType: step.systemType,
              label: step.label,
              status: "NOT_REQUESTED",
              notes: `Step ${index + 1} of GA/GSC setup`,
            },
          });
        } else {
          await prisma.launchChecklistItem.create({
            data: {
              clientId,
              label: step.label,
              order: index,
            },
          });
        }
      }
      break;

    case "PROPOSAL_LINE": {
      const pricingId = config.pricingMatrixItemId
        ? String(config.pricingMatrixItemId)
        : null;
      const item = pricingId
        ? await prisma.pricingMatrixItem.findUnique({ where: { id: pricingId } })
        : null;

      let proposal = await prisma.proposal.findFirst({
        where: { clientId, status: "DRAFT" },
      });

      if (!proposal) {
        proposal = await prisma.proposal.create({
          data: { clientId, status: "DRAFT" },
        });
      }

      const unitPrice = item?.basePrice ?? 0;
      const qty = Number(config.quantity ?? 1);
      await prisma.proposalLineItem.create({
        data: {
          proposalId: proposal.id,
          description: item?.name ?? String(config.description ?? "Service"),
          quantity: qty,
          unitPrice,
          total: Number(unitPrice) * qty,
        },
      });
      break;
    }

    default:
      break;
  }
}

export async function processOnboardingSubmission(input: {
  sessionId: string;
  token: string;
  responses: Answers;
  template: OnboardingTemplate & { rules: OnboardingRule[] };
  leadId: string;
}) {
  const client = await ensureClientFromLead(input.leadId);

  for (const rule of input.template.rules) {
    if (evaluateCondition(rule.condition, input.responses)) {
      await applyRule(rule, client.id, input.leadId, input.responses);
    }
  }

  await prisma.onboardingSession.update({
    where: { id: input.sessionId },
    data: {
      clientId: client.id,
      responses: input.responses as Prisma.InputJsonValue,
      status: "COMPLETED",
      completedAt: new Date(),
    },
  });

  await prisma.lead.update({
    where: { id: input.leadId },
    data: { status: "QUESTIONNAIRE_COMPLETED" },
  });

  await emitSystemEvent({
    type: SYSTEM_EVENT_TYPES.ONBOARDING_COMPLETED,
    clientId: client.id,
    leadId: input.leadId,
    payload: { sessionId: input.sessionId },
  });

  return client;
}
