"use server";

import { revalidatePath } from "next/cache";
import { redirect, notFound } from "next/navigation";
import type { LeadStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth/session";
import {
  createLeadSchema,
  updateLeadSchema,
  updateLeadStatusSchema,
  discoveryCallSchema,
} from "@/lib/validation/leads";

async function createLeadTasks(leadId: string, website?: string | null) {
  const tasks = [
    {
      leadId,
      title: "Book discovery call",
      autoGenerated: true,
      source: "lead_created",
    },
    {
      leadId,
      title: "Send intake questionnaire",
      autoGenerated: true,
      source: "lead_created",
    },
  ];

  if (website) {
    tasks.push({
      leadId,
      title: "Review existing website/GBP",
      autoGenerated: true,
      source: "lead_created",
    });
  }

  await prisma.task.createMany({ data: tasks });
}

function parseDate(value?: string) {
  if (!value) return undefined;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? undefined : date;
}

export async function getLeads() {
  await requireAdmin();
  return prisma.lead.findMany({
    orderBy: { updatedAt: "desc" },
    include: {
      client: { select: { id: true } },
      _count: { select: { tasks: true } },
    },
  });
}

export async function getLead(id: string) {
  await requireAdmin();
  return prisma.lead.findUnique({
    where: { id },
    include: {
      discoveryCall: true,
      client: { select: { id: true, legalBusinessName: true } },
      tasks: { orderBy: { createdAt: "asc" } },
    },
  });
}

export async function createLead(formData: FormData): Promise<void> {
  await requireAdmin();

  const raw = {
    businessName: formData.get("businessName"),
    contactName: formData.get("contactName"),
    email: formData.get("email"),
    phone: formData.get("phone") || undefined,
    website: formData.get("website") || undefined,
    location: formData.get("location") || undefined,
    serviceArea: formData.get("serviceArea") || undefined,
    industry: formData.get("industry") || undefined,
    urgency: formData.get("urgency") || undefined,
    budgetRange: formData.get("budgetRange") || undefined,
    problemSummary: formData.get("problemSummary") || undefined,
    source: formData.get("source") || undefined,
    interestedIn: formData.getAll("interestedIn").map(String),
  };

  const parsed = createLeadSchema.safeParse(raw);
  if (!parsed.success) {
    return;
  }

  const data = parsed.data;
  const lead = await prisma.lead.create({
    data: {
      ...data,
      website: data.website || null,
    },
  });

  await createLeadTasks(lead.id, data.website);
  revalidatePath("/leads");
  redirect(`/leads/${lead.id}`);
}

export async function updateLead(formData: FormData): Promise<void> {
  await requireAdmin();

  const raw = {
    id: formData.get("id"),
    businessName: formData.get("businessName") || undefined,
    contactName: formData.get("contactName") || undefined,
    email: formData.get("email") || undefined,
    phone: formData.get("phone") || undefined,
    website: formData.get("website") || undefined,
    location: formData.get("location") || undefined,
    serviceArea: formData.get("serviceArea") || undefined,
    industry: formData.get("industry") || undefined,
    urgency: formData.get("urgency") || undefined,
    budgetRange: formData.get("budgetRange") || undefined,
    problemSummary: formData.get("problemSummary") || undefined,
    source: formData.get("source") || undefined,
    interestedIn: formData.getAll("interestedIn").map(String),
    status: formData.get("status") || undefined,
    lossReason: formData.get("lossReason") || undefined,
  };

  const parsed = updateLeadSchema.safeParse(raw);
  if (!parsed.success) {
    return;
  }

  const { id, status, lossReason, ...fields } = parsed.data;

  if (status === "LOST" && !lossReason) {
    return;
  }

  await prisma.lead.update({
    where: { id },
    data: {
      ...fields,
      website: fields.website || null,
      ...(status ? { status, lossReason: status === "LOST" ? lossReason : null } : {}),
    },
  });

  revalidatePath("/leads");
  revalidatePath(`/leads/${id}`);
}

export async function updateLeadStatus(input: {
  id: string;
  status: LeadStatus;
  lossReason?: string;
}): Promise<{ error?: string; success?: boolean }> {
  await requireAdmin();

  const parsed = updateLeadStatusSchema.safeParse(input);
  if (!parsed.success) {
    return { error: "Invalid status update" };
  }

  const { id, status, lossReason } = parsed.data;
  if (status === "LOST" && !lossReason) {
    return { error: "Loss reason is required" };
  }

  await prisma.lead.update({
    where: { id },
    data: {
      status,
      lossReason: status === "LOST" ? lossReason : null,
    },
  });

  revalidatePath("/leads");
  revalidatePath(`/leads/${id}`);
  return { success: true };
}

export async function upsertDiscoveryCall(formData: FormData): Promise<void> {
  await requireAdmin();

  const raw = {
    leadId: formData.get("leadId"),
    scheduledAt: formData.get("scheduledAt") || undefined,
    completedAt: formData.get("completedAt") || undefined,
    notes: formData.get("notes") || undefined,
    summary: formData.get("summary") || undefined,
    decisionMaker: formData.get("decisionMaker") === "on",
    responsivenessNote: formData.get("responsivenessNote") || undefined,
    painPoints: formData.get("painPoints") || undefined,
    seasonalPatterns: formData.get("seasonalPatterns") || undefined,
    topServices: formData.get("topServices") || undefined,
    hasGBP: formData.get("hasGBP") === "on",
    hasDomainAccess: formData.get("hasDomainAccess") === "on",
    hasAnalyticsAccess: formData.get("hasAnalyticsAccess") === "on",
    hasAdsAccount: formData.get("hasAdsAccount") === "on",
    fitDecision: formData.get("fitDecision") || undefined,
  };

  const parsed = discoveryCallSchema.safeParse(raw);
  if (!parsed.success) {
    return;
  }

  const { leadId, scheduledAt, completedAt, fitDecision, ...rest } = parsed.data;

  await prisma.discoveryCall.upsert({
    where: { leadId },
    create: {
      leadId,
      scheduledAt: parseDate(scheduledAt),
      completedAt: parseDate(completedAt),
      fitDecision: fitDecision ?? null,
      ...rest,
    },
    update: {
      scheduledAt: parseDate(scheduledAt),
      completedAt: parseDate(completedAt),
      fitDecision: fitDecision ?? null,
      ...rest,
    },
  });

  revalidatePath(`/leads/${leadId}`);
}

export async function convertLeadToClient(leadId: string): Promise<void> {
  await requireAdmin();

  const lead = await prisma.lead.findUnique({
    where: { id: leadId },
    include: { client: true },
  });

  if (!lead) {
    notFound();
  }
  if (lead.client) {
    redirect(`/clients/${lead.client.id}`);
  }

  const client = await prisma.client.create({
    data: {
      leadId: lead.id,
      legalBusinessName: lead.businessName,
      billingName: lead.contactName,
      billingEmail: lead.email,
      status: "ONBOARDING",
      brandProfile: {
        create: {
          phonePrimary: lead.phone,
          industry: lead.industry,
          serviceAreas: lead.serviceArea ? [lead.serviceArea] : [],
          existingSiteUrl: lead.website,
          budgetRange: lead.budgetRange,
          gbpCategoriesSecondary: [],
          exampleSites: [],
        },
      },
    },
  });

  revalidatePath("/leads");
  revalidatePath("/clients");
  redirect(`/clients/${client.id}`);
}

export async function convertLeadToClientAction(formData: FormData): Promise<void> {
  const leadId = formData.get("leadId");
  if (typeof leadId !== "string") return;
  await convertLeadToClient(leadId);
}
