import { CITATION_DIRECTORIES } from "./citation-directories";
import { MONTHLY_SOP_ITEMS } from "./monthly-sops";
import { prisma } from "@/lib/prisma";

export async function seedCitationsForClient(clientId: string) {
  const existing = await prisma.citationRecord.count({ where: { clientId } });
  if (existing > 0) return;

  await prisma.citationRecord.createMany({
    data: CITATION_DIRECTORIES.map((d) => ({
      clientId,
      directory: d.directory,
      status: "NOT_STARTED",
    })),
  });
}

export async function generateMonthlyMaintenanceChecklist(
  clientId: string,
  periodMonth: number,
  periodYear: number
) {
  const existing = await prisma.maintenanceChecklist.findUnique({
    where: {
      clientId_periodMonth_periodYear: { clientId, periodMonth, periodYear },
    },
  });
  if (existing) return existing;

  const items = MONTHLY_SOP_ITEMS.filter((item) => {
    if (item.cadence === "quarterly") return periodMonth % 3 === 1;
    if (item.cadence === "annual") return periodMonth === 1;
    return true;
  });

  return prisma.maintenanceChecklist.create({
    data: {
      clientId,
      periodMonth,
      periodYear,
      items: {
        create: items.map((item) => ({
          category: item.category,
          label: `Week ${item.week}: ${item.label}`,
          order: item.order,
          autoGenerated: true,
        })),
      },
    },
    include: { items: true },
  });
}
